// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLmOmKE1KG_EKVQUT0N7BDUns-eTa5BXA',
    appId: '1:674677862312:web:f010d08d74492812d3f79d',
    messagingSenderId: '674677862312',
    projectId: 'login-9a64b',
    authDomain: 'login-9a64b.firebaseapp.com',
    storageBucket: 'login-9a64b.appspot.com',
    measurementId: 'G-7BCDX3G813',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-nLBTfiQ9dVyAu8DwB7X38eQ_NXUKVlc',
    appId: '1:674677862312:android:ea05aa7103c6a3a2d3f79d',
    messagingSenderId: '674677862312',
    projectId: 'login-9a64b',
    storageBucket: 'login-9a64b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmAfi2XWcs1eCPr81fLA1JF91BOGdO_PA',
    appId: '1:674677862312:ios:ebd59fd05eefcf72d3f79d',
    messagingSenderId: '674677862312',
    projectId: 'login-9a64b',
    storageBucket: 'login-9a64b.appspot.com',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmAfi2XWcs1eCPr81fLA1JF91BOGdO_PA',
    appId: '1:674677862312:ios:826129ff6cd26981d3f79d',
    messagingSenderId: '674677862312',
    projectId: 'login-9a64b',
    storageBucket: 'login-9a64b.appspot.com',
    iosBundleId: 'com.example.loginApp.RunnerTests',
  );
}
